// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnxqjqfaevfcupqiquuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZueHFqcWZhZXZmY3VwcWlxdXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODczNTksImV4cCI6MjA2Njg2MzM1OX0.B2QAkLBkG_3QjGN5RuIqd-KBZEjiq7ry9HnqyRxRmXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});